sonar.projectKey=dorak-backend
sonar.projectName=Dorak Backend
sonar.sources=modules,config,database,bootstrap,routes
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=junit.xml
sonar.exclusions=\
bootstrap/cache/**,\
storage/**,\
vendor/**,\
public/**,\
node_modules/**,\
**/*.blade.php,\
modules/*/Database/Seeders/**,\
modules/*/Database/Factories/**
sonar.coverage.exclusions=\
routes/**,\
config/**,\
database/**,\
bootstrap/**,\
modules/*/Routes/**,\
modules/*/Config/**
